print("AND")
print("True And True =>", True and True)
print("True And False =>", True and False)
print("False And True =>", False and True)
print("False And False =>", False and False)
print(10 > 5 and 5 < 10)
print(10 > 5 and 5 > 10)
stock = int(input("ingresa la cantidad de su stock"))
print(stock >= 100 and stock <= 1000)
print("-" * 20)
print("OR")
print("True OR True =>", True or True)
print("True OR False =>", True or False)
print("False OR True =>", False or True)
print("False OR False =>", False or False)
role = str(input("cual es tu puto roal squinkle"))

print(role == 'admin' or role == 'seller')
